### ISSUE TITLE
gradle build error

### ISSUE THREAD

**Issue by banq** [michal-michaluk/factory#17]
Could not find method annotationProcessor() for arguments [org.projectlombok:lombok:1.18.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by michal-michaluk** [comment]
Thx for feedback,
do you use gradle wrapper or your own gradle installation?
If it is your own grade installation, what gradle version do you have?

**Comment by banq** [comment]
ok, my gradle version is 4.5.1, now upgrade to 4.8 , all ok ,thanks

**Comment by michal-michaluk** [comment]
In case of any further questions, don't hesitate to contact me on twitter @michal_michaluk.
