### ISSUE TITLE
Try to lower the initial hurdle

### ISSUE THREAD

**Issue by OLibutzki** [michal-michaluk/factory#18]
Hi everyone,

I really like this project as you implement the DDD idea in a clean way. Thanks for that!

For me the entry was quite hard as the project lacks some useful information:

1. I did not find a description / specification of the business your application reflects. Because you use DDD it can be derived from the structure of the modules and the domain objects, but in my opinion it would be very helpful to describe the requirements of the application separately and more deeply.
1. It would be very helpful to have some support how to interact with the application. Having some UIs would be great, but providing some examples how the REST requests need to look like in order to do certain things (create product for instance) helps as well in the first place.

My suggestion from a consumer's point of view: Keep up the good work, but add some artifacts which lower the initial hurdle for interested parties.

**Comment by michal-michaluk** [comment]
Thank You,
it will Take few days to fix point 1., but I’m starting instantly.
For UI some help will be needed, so i’m Not able go give any timeline on that, but mockups in docs can be done in next weeks.

**Comment by OLibutzki** [comment]
Sound great, thanks. If you have any results, I'm very keen on reviewing your outcome from a user's point of view.

**Comment by OLibutzki** [comment]
Hi @michal-michaluk, any progress so far? ;-)

**Comment by michal-michaluk** [comment]
Hi, to be honest I did a bit in that area "long time ago", but had no time to publish it, thanks for impulse to do that.
Could you please review the material and give some hints how to improve it, then I will integrate it with README.
Some links:
Introduction video leveraging Event Storming notation (5min but boring)
https://youtu.be/OBrXisnTW-4

Brief Demand Forecasting domain description with some animated simplified DFD diagrams
https://github.com/ddd-by-examples/factory/blob/doc/domain-explanation/doc/demand-forecasting/README.md

**Comment by OLibutzki** [comment]
That's very helpful. I just realized that https://github.com/ddd-by-examples/factory/blob/doc/domain-explanation/doc/demand-forecasting/README.md exists since July 2018. Honstely, I didn't noticed this document as it is not referenced from the main README.md file.

The video is very cool. I like the way you explain certain aspects. For me this is sufficient to understand what the domain is all about.
